format = """
${custom.dotfiles}\
$all
"""

[gcloud]
disabled = true

[directory]
truncation_length = 4
truncate_to_repo = false

[env_var]
variable = "STARSHIP_SHELL_ARCH"
style = "bold yellow"
format = "[$env_value]($style) "

[custom.dotfiles]
command = "cd ~/dotfiles && git rev-parse @{upstream} > /dev/null 2>&1 && echo \"[dotfiles*]\""
when = "test -d ~/dotfiles/.git"
format = "$output"

